name: Execução Diária

on:
  schedule:
    - cron: '0 5 * * *'  # Agendado para executar todos os dias às 2 da manhã

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v2

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Especifique a versão do Python que você está usando

    - name: Instalação das Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Se você tiver um arquivo requirements.txt

    - name: Execução do Script
      run: python -m cs_integration

