name: integration-sheets_circle
#execution
on:
  push:
    branches:
      - master  # Substitua "main" pelo nome da sua branch principal, se for diferente

  schedule:
    - cron: '0 5 * * *'  # Agendado para executar todos os dias às 2 da manhã

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v2

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.3'  # Especifique a versão do Python que você está usando
      
    - name: Set up Google Service Account Key
      run: echo '${{ secrets.CRED_JSON }}' > service_account_key.json  
    - name: Print File Content
      run: cat service_account_key.json


    - name: Instalação das Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Execução do Script
      run: python -m cs_integration
      env:
        PLATFORM-CLIENT-ID: ${{ secrets.PLATFORM_CLIENT_ID }}
        PLATFORM-CLIENT-SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        PLATFORM-PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
        PLATFORM-USERNAME: ${{ secrets.PLATFORM_USERNAME }}
        SHEET_ID: ${{ secrets.SHEET_ID}}


