name: integration-sheets_circle
#execution
on:
  push:
    branches:
      - master  # Substitua "main" pelo nome da sua branch principal, se for diferente

  schedule:
    - cron: '0 5 * * *'  # Agendado para executar todos os dias às 2 da manhã

jobs:
  build:
    runs-on: ubuntu-latest
    environment: scf_automation
    env:
      PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
      PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID}}
      CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL}}

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.3'  # Especifique a versão do Python que você está usando

    - name: Listar Conteúdo do Diretório
      run: ls -la

    - name: Instalação das Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Execução do Script
      run: python -m cs_integration

        
